[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["foundry-devops/=lib/foundry-devops/", "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/", "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
